### ISSUE TITLE
Calculator horizontal scrolling and scrollbar issues

### ISSUE THREAD

**Issue by MarceloRuiz** [linuxmint/gnome-apps#33]
If the user types several numbers, the horizontal scrolling should show the last numbers typed (the right side). Also the scrollbar should not appear on top of the numbers partially covering them, but underneath.

**Comment by JosephMcc** [comment]
You have a legitimate point but we don't maintain gnome-calculator. You need to open the issue upstream with gnome.

**Comment by MarceloRuiz** [comment]
I just saw that calculator in gnome has version 6.6.x and in Cinnamon we're using 3.18.x
I am wondering if this has been solved on newer versions. Why is the version in Sarah not closer to the current last version?
Anyway, I opened the bug report: [https://bugzilla.gnome.org/show_bug.cgi?id=770246](url)
Thanks

**Comment by JosephMcc** [comment]
We use the version that comes from Ubuntu Xenial. With most gnome apps the versions are tied to the current gtk version. That's because in many cases a newer version (say 3.20) will also require the newer gtk version.

Looking here https://github.com/GNOME/gnome-calculator I'm not sure where you are getting the version 6.6 from.

**Comment by MarceloRuiz** [comment]
I was getting it from the bug report form. Thanks for the explanation, though 


Sent on the new Sprint Network from my Samsung Galaxy S®4

-------- Original message --------
